# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
encoding: UTF-8 
timezone: Europe/Moscow 

# Setup
title:            Robiul Islam
tagline:          
description:      
url:              
baseurl:          /newversion/
markdown: kramdown 
highlighter: rouge 

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
